/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tadeo
 */
public class Libros extends javax.swing.JPanel {

    /**
     * Creates new form Libros
     */
    public Libros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLibros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableDatos = new javax.swing.JTable();
        btnLibros = new javax.swing.JButton();
        btnNuevosLibros = new javax.swing.JButton();

        panelLibros.setBackground(new java.awt.Color(216, 217, 218));

        JTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Libro", "Nombre", "Autor", "Stock", "Total"
            }
        ));
        jScrollPane1.setViewportView(JTableDatos);

        btnLibros.setText("Libros");
        btnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosActionPerformed(evt);
            }
        });

        btnNuevosLibros.setText("Nuevos Libros");
        btnNuevosLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevosLibrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLibrosLayout = new javax.swing.GroupLayout(panelLibros);
        panelLibros.setLayout(panelLibrosLayout);
        panelLibrosLayout.setHorizontalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addGroup(panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevosLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );
        panelLibrosLayout.setVerticalGroup(
            panelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addGap(26, 26, 26))
            .addGroup(panelLibrosLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(105, 105, 105)
                .addComponent(btnNuevosLibros, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(125, 125, 125))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevosLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevosLibrosActionPerformed
        // TODO add your handling code here:
        Paneles.CorreoLibrero panel = new Paneles.CorreoLibrero();
        
        panel.setSize(818,410);
        panel.setLocation(0,0);
        
        panelLibros.removeAll();
        panelLibros.add(panel,BorderLayout.CENTER);
        panelLibros.revalidate();
        panelLibros.repaint();
        
        
        
    }//GEN-LAST:event_btnNuevosLibrosActionPerformed

    private void btnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosActionPerformed
        // Boton que mostrara los libros que hay en la base de datos en la tabla.
        
        JTable table =JTableDatos;
       DefaultTableModel modelo =(DefaultTableModel) table.getModel();
        
            try{
            ConexionBd.Conexion objetoConexion = new ConexionBd.Conexion();
            Connection con =objetoConexion.establecerConexion();
            PreparedStatement preparaConsulta= null; 
            ResultSet rs=null;
            if (con != null){
                
                
                String tablas = "SELECT idlibros,nombre,autor,libros_disponibles,libros_total FROM biblio_usuarios.libros";
                //PreparedStatement preparaConsulta = con.prepareStatement(tablas);
                preparaConsulta =objetoConexion.establecerConexion().prepareStatement(tablas);
                rs=preparaConsulta.executeQuery();
               // ResultSet rs =preparaConsulta.executeQuery();
                
                JTable tabla =JTableDatos;
                DefaultTableModel model = (DefaultTableModel) tabla.getModel();
                
                model.setRowCount(0);
                
                while(rs.next()){
                    Object[] columnas={
                       rs.getObject("idlibros"),
                       rs.getObject("nombre"),
                       rs.getObject("autor"),
                       rs.getObject("libros_disponibles"),
                       rs.getObject("libros_total"),
                    };
                    
                    model.addRow(columnas);
                }//Fin del bucle while
                //Cerrar recursos
                rs.close();
                preparaConsulta.close();
                con.close();
                //fin condicional if 
            }else{
                JOptionPane.showMessageDialog(null,"No se pudo mostra fin");
             }//Fin else 
            }//Fin try
            catch(Exception e ){
                JOptionPane.showMessageDialog(null,"No " +e.getMessage());
            }
    }//GEN-LAST:event_btnLibrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableDatos;
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnNuevosLibros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelLibros;
    // End of variables declaration//GEN-END:variables
}
