/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Paneles;

import java.awt.BorderLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tadeo
 */
public class Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUsuarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaUsuarios = new javax.swing.JTable();
        btnUsuarios = new javax.swing.JButton();
        btnPedir = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();

        panelUsuarios.setBackground(new java.awt.Color(216, 217, 218));
        panelUsuarios.setPreferredSize(new java.awt.Dimension(818, 410));

        JTablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Correo", "ID usuario", "Deuda"
            }
        ));
        jScrollPane1.setViewportView(JTablaUsuarios);

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnPedir.setText("Pedir un Libro");
        btnPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirActionPerformed(evt);
            }
        });

        btnDevolver.setText("Devolver Libro");
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUsuariosLayout = new javax.swing.GroupLayout(panelUsuarios);
        panelUsuarios.setLayout(panelUsuariosLayout);
        panelUsuariosLayout.setHorizontalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addGap(69, 69, 69)
                .addGroup(panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPedir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );
        panelUsuariosLayout.setVerticalGroup(
            panelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addGap(39, 39, 39))
            .addGroup(panelUsuariosLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(72, 72, 72)
                .addComponent(btnPedir, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(75, 75, 75)
                .addComponent(btnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // este boton cambia de panel
        Paneles.DevolverLibros panel = new Paneles.DevolverLibros();
        
        panel.setSize(818,410);
        panel.setLocation(0,0);
        
        panelUsuarios.removeAll();
        panelUsuarios.add(panel,BorderLayout.CENTER);
        panelUsuarios.revalidate();
        panelUsuarios.repaint();
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void btnPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirActionPerformed
        // TODO add your handling code here:
        Paneles.PedirLibro panel = new Paneles.PedirLibro();
        
        panel.setSize(818,410);
        panel.setLocation(0,0);
        
        panelUsuarios.removeAll();
        panelUsuarios.add(panel,BorderLayout.CENTER);
        panelUsuarios.revalidate();
        panelUsuarios.repaint();
    }//GEN-LAST:event_btnPedirActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        
        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            ConexionBd.Conexion objetoConexion = new ConexionBd.Conexion();
            String consulta = "SELECT  id,nombre,correo,idUsuario,nombreLibro FROM biblio_usuarios.almacenamiento;";
            ps = objetoConexion.establecerConexion().prepareStatement(consulta);

            rs = ps.executeQuery();

            JTable tabla = JTablaUsuarios;
            DefaultTableModel model = (DefaultTableModel) tabla.getModel();

            model.setRowCount(0);

            while (rs.next()) {
                Object[] Columnas = {
                    rs.getObject("id"),
                    rs.getObject("nombre"),
                    rs.getObject("correo"),
                    rs.getObject("idUsuario"),
                    rs.getObject("nombreLibro")
                };
                model.addRow(Columnas);
            }

        } catch (Exception e) {

        }
        
    }//GEN-LAST:event_btnUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTablaUsuarios;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnPedir;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelUsuarios;
    // End of variables declaration//GEN-END:variables
}
